---
engines:
 coverage:
   enabled: true
   exclude_paths:
     - teshsuite/**
exclude_paths:
  - src/*_unit.c*
  - teshsuite/smpi/mpich3-test/**
  - teshsuite/smpi/isp/**
  - **/*_dtd.c
  - **/*_dtd.h
  - **/*yy.c
  - src/xbt/automaton/parserPromela.tab.*
  - src/smpi/colls/**/*
  - examples/smpi/NAS/*
  - src/xbt/RngStream.c
  - include/xbt/RngStream.h
  