image: simgrid/build-deps

pages:
  script:
  - pip3 install --requirement docs/requirements.txt 
  - cd docs
  - LC_ALL=C.UTF-8 ./Build.sh
  - mv build/html ../public
  artifacts:
    paths:
    - public
  only:
  - master

ctest:
  script:
  - cmake -Denable_model-checking=OFF -Denable_documentation=OFF -Denable_coverage=ON -Denable_java=ON -Denable_lua=OFF -Denable_compile_optimizations=ON -Denable_smpi=ON -Denable_smpi_MPICH3_testsuite=ON -Denable_compile_warnings=ON .
  - make VERBOSE=1 && ctest --output-on-failure
